### ISSUE TITLE
Indexer: Invalid attribute type

### ISSUE THREAD

**Issue by m-overlund** [meanbee/magento-runrate#1]
Have installed the module on Magento 1.9.3.1, but when i try to reindex Run Rate I get this "Invalid attribute type" error.

Can you guys maybe give me a hint to fix this error?

![screen shot 2017-03-30 at 19 31 56](https://cloud.githubusercontent.com/assets/504236/24517803/f1c1831e-157f-11e7-9323-00f4dca1b7ca.png)

**Comment by pauldpauld** [comment]
Hi m-overlund,
same here, I am on 1.7.0.2
Update:
Table has been correctly installed (I use table prefix).
Extension appears in menu (suggests as it is empty, re-index may be required).

We didn't read the instuctions!
you/I need to add a new attribute https://meanbee.atlassian.net/wiki/display/EXT/Inventory+Run+Rate

CONFIRMED: reading the instructions properly helps :-(
Extension now working, Thanks Meanbee

Regards, Paul

**Comment by punkstar** [comment]
Thanks Paul.  I've added the instructions to the wiki on this repository.
